guider:
  defaults:
    - _self_

  seed: 42
  use_distributed: True
  notes: None

  agcrn: "outputs/AGCRN/05-13_20-02/best_model.pth"
  ################################################################ Adjustable
  num_workers: 30
  lr_init: 0.003

  # Adjust for quick testing
  batch_size: 64
  epochs: 200
  num_batches_to_process: "inf"
  diffusion_steps: 1000
  wandb_mode: "run"
  timestep_respacing_val_test: ${diffusion_steps}
  ################################################################

  # Diffusion model
  dif_model:
    N: ${diffusion_steps}
    sample_steps: ${diffusion_steps}
    beta_end: 0.02
    V: 170
    model_name: "DiffSTG"
    is_test: false
    optimizer: "adam"
    wd: 0.00001
    start_epoch: 0
    AGCRN:
      num_nodes: 170
      T_p: 12
      T_h: 12
      input_dim: 1
      output_dim: 1
      embed_dim: 2
      rnn_units: 64
      num_layers: 2
      cheb_k: 2
    data:
      centered: true
      image_size: ${dif_model.AGCRN.T_p}
      num_channels: ${dif_model.AGCRN.input_dim}
    model:
      attn_resolutions: [6]
      ch_mult: [1, 2]
      conditional: true
      dropout: 0.1
      ema_rate: 0.9999
      name: ddpm_guider
      nf: 64
      nonlinearity: swish
      normalization: GroupNorm
      num_res_blocks: 2
      resamp_with_conv: true
      # optimizer
      beta1: 0.9
      eps: 1.0e-08
      weight_decay: 0
      warmup: 30
      grad_clip: 1.
      # sde
      num_scales: 1000
      beta_min: 0.1
      beta_max: 20.

  # dir
  best_model_path: ${log_dir} # "/hpc2hdd/home/mgong081/Projects/diffusion_GNNs_0202/outputs/DSTGCRN/04-05_11-02/"
  best_model_name: best_model.pth
  wandb_project_name: "guider_training"

  NOW: ${now:%m-%d_%H-%M}
  log_dir: outputs/DSTGCRN/${NOW}

  hydra:
    run:
      dir: ${log_dir}

  # wandb
  wandb_dir: ${log_dir}
  run_name: ${NOW}

  early_stop: True
  early_stop_patience: 15

  device: cuda:0

  #  Data
  data_path: "data/raw/pems08.npz"
  val_ratio: 0.2
  test_ratio: 0.2

  normalizer: std # None
  column_wise: False
